//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        internal static string btnSignUp {
            get {
                return ResourceManager.GetString("btnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        internal static string chkRememberPassword {
            get {
                return ResourceManager.GetString("chkRememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor code must be numeric.
        /// </summary>
        internal static string Doctor_code_must_be_numeric {
            get {
                return ResourceManager.GetString("Doctor code must be numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor ID not found.
        /// </summary>
        internal static string Doctor_ID_not_found {
            get {
                return ResourceManager.GetString("Doctor ID not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        internal static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keyword you want to search.
        /// </summary>
        internal static string Enter_the_keyword_you_want_to_search {
            get {
                return ResourceManager.GetString("Enter the keyword you want to search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name, last name, License Number and Schedule is not null.
        /// </summary>
        internal static string First_name__last_name__License_Number_and_Schedule_is_not_null {
            get {
                return ResourceManager.GetString("First name, last name, License Number and Schedule is not null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name, last name and social security number is not null.
        /// </summary>
        internal static string First_name__last_name_and_social_security_number_is_not_null {
            get {
                return ResourceManager.GetString("First name, last name and social security number is not null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconAboutSoftware {
            get {
                object obj = ResourceManager.GetObject("iconAboutSoftware", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconAppointmentScheduleReport {
            get {
                object obj = ResourceManager.GetObject("iconAppointmentScheduleReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconBackupandRestoreDatabase {
            get {
                object obj = ResourceManager.GetObject("iconBackupandRestoreDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconChangePassword {
            get {
                object obj = ResourceManager.GetObject("iconChangePassword", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconClose {
            get {
                object obj = ResourceManager.GetObject("iconClose", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconContactSupport {
            get {
                object obj = ResourceManager.GetObject("iconContactSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconDarkMode {
            get {
                object obj = ResourceManager.GetObject("iconDarkMode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconDarkMode_ {
            get {
                object obj = ResourceManager.GetObject("iconDarkMode_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconExit {
            get {
                object obj = ResourceManager.GetObject("iconExit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconInventoryandMedicineRevenueReport {
            get {
                object obj = ResourceManager.GetObject("iconInventoryandMedicineRevenueReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconLightMode {
            get {
                object obj = ResourceManager.GetObject("iconLightMode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconLogin {
            get {
                object obj = ResourceManager.GetObject("iconLogin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconLogout {
            get {
                object obj = ResourceManager.GetObject("iconLogout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageAppointments {
            get {
                object obj = ResourceManager.GetObject("iconManageAppointments", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageDoctors {
            get {
                object obj = ResourceManager.GetObject("iconManageDoctors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageExaminationHistory {
            get {
                object obj = ResourceManager.GetObject("iconManageExaminationHistory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageMedicineInventory {
            get {
                object obj = ResourceManager.GetObject("iconManageMedicineInventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManagePatients {
            get {
                object obj = ResourceManager.GetObject("iconManagePatients", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManagePrescription {
            get {
                object obj = ResourceManager.GetObject("iconManagePrescription", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageUserAccounts {
            get {
                object obj = ResourceManager.GetObject("iconManageUserAccounts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconPatientListReport {
            get {
                object obj = ResourceManager.GetObject("iconPatientListReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconUSA {
            get {
                object obj = ResourceManager.GetObject("iconUSA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconUserGuide {
            get {
                object obj = ResourceManager.GetObject("iconUserGuide", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconVietNam {
            get {
                object obj = ResourceManager.GetObject("iconVietNam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconVietNam_ {
            get {
                object obj = ResourceManager.GetObject("iconVietNam_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconViewActivityLog {
            get {
                object obj = ResourceManager.GetObject("iconViewActivityLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] img001 {
            get {
                object obj = ResourceManager.GetObject("img001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] img002 {
            get {
                object obj = ResourceManager.GetObject("img002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] img003 {
            get {
                object obj = ResourceManager.GetObject("img003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] imgfrmCreateAccount {
            get {
                object obj = ResourceManager.GetObject("imgfrmCreateAccount", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] imgfrmLoginForm {
            get {
                object obj = ResourceManager.GetObject("imgfrmLoginForm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s available.
        /// </summary>
        internal static string It_s_available {
            get {
                return ResourceManager.GetString("It\'s available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string lblHello {
            get {
                return ResourceManager.GetString("lblHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where health begins, technology leads the way.
        /// </summary>
        internal static string lblLogan {
            get {
                return ResourceManager.GetString("lblLogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer.
        /// </summary>
        internal static string lblSecurityAnswer {
            get {
                return ResourceManager.GetString("lblSecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        internal static string lblSecurityQuestion {
            get {
                return ResourceManager.GetString("lblSecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigup.
        /// </summary>
        internal static string lblSigup {
            get {
                return ResourceManager.GetString("lblSigup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Role.
        /// </summary>
        internal static string lblUsersRole {
            get {
                return ResourceManager.GetString("lblUsersRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked, cannot be removed.
        /// </summary>
        internal static string Linked__cannot_be_removed {
            get {
                return ResourceManager.GetString("Linked, cannot be removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string llblDontHaveAnAccount {
            get {
                return ResourceManager.GetString("llblDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string llblForgotPassword {
            get {
                return ResourceManager.GetString("llblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ID yet.
        /// </summary>
        internal static string No_ID_yet {
            get {
                return ResourceManager.GetString("No ID yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patient ID.
        /// </summary>
        internal static string No_patient_ID {
            get {
                return ResourceManager.GetString("No patient ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patients yet.
        /// </summary>
        internal static string No_patients_yet {
            get {
                return ResourceManager.GetString("No patients yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string Not_found {
            get {
                return ResourceManager.GetString("Not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string notif_ {
            get {
                return ResourceManager.GetString("notif_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully!.
        /// </summary>
        internal static string notif_frmCreateAccount_Created {
            get {
                return ResourceManager.GetString("notif_frmCreateAccount_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation failed.
        /// </summary>
        internal static string notif_frmCreateAccount_CreateFailed {
            get {
                return ResourceManager.GetString("notif_frmCreateAccount_CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        internal static string notif_frmCreateAccount_Fill {
            get {
                return ResourceManager.GetString("notif_frmCreateAccount_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password authentication mismatch.
        /// </summary>
        internal static string notif_frmCreateAccount_PassMiss {
            get {
                return ResourceManager.GetString("notif_frmCreateAccount_PassMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered wrong password 3 times, software will close now!.
        /// </summary>
        internal static string notif_frmLogin_Closed {
            get {
                return ResourceManager.GetString("notif_frmLogin_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  time.
        /// </summary>
        internal static string notif_frmLogin_CountTime {
            get {
                return ResourceManager.GetString("notif_frmLogin_CountTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account and password.
        /// </summary>
        internal static string notif_frmLogin_EnterUserAndPass {
            get {
                return ResourceManager.GetString("notif_frmLogin_EnterUserAndPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during login: .
        /// </summary>
        internal static string notif_frmLogin_Error {
            get {
                return ResourceManager.GetString("notif_frmLogin_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string notif_frmLogin_LoginSuccessful {
            get {
                return ResourceManager.GetString("notif_frmLogin_LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not correct, do you want to create a new user?.
        /// </summary>
        internal static string notif_frmLogin_NotFound {
            get {
                return ResourceManager.GetString("notif_frmLogin_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name .
        /// </summary>
        internal static string notif_frmLogin_UserName {
            get {
                return ResourceManager.GetString("notif_frmLogin_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong password .
        /// </summary>
        internal static string notif_frmLogin_WrongPassword {
            get {
                return ResourceManager.GetString("notif_frmLogin_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID not found.
        /// </summary>
        internal static string Patient_ID_not_found {
            get {
                return ResourceManager.GetString("Patient ID not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a line to edit.
        /// </summary>
        internal static string Select_a_line_to_edit {
            get {
                return ResourceManager.GetString("Select a line to edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string tabPageAppointments {
            get {
                return ResourceManager.GetString("tabPageAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string tabPageDoctors {
            get {
                return ResourceManager.GetString("tabPageDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Inventory.
        /// </summary>
        internal static string tabPageMedicineInventory {
            get {
                return ResourceManager.GetString("tabPageMedicineInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string tabPagePatients {
            get {
                return ResourceManager.GetString("tabPagePatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Software.
        /// </summary>
        internal static string tsmiAboutSoftware {
            get {
                return ResourceManager.GetString("tsmiAboutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment ScheduleReport.
        /// </summary>
        internal static string tsmiAppointmentScheduleReport {
            get {
                return ResourceManager.GetString("tsmiAppointmentScheduleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup And Restore Database.
        /// </summary>
        internal static string tsmiBackupAndRestoreDatabase {
            get {
                return ResourceManager.GetString("tsmiBackupAndRestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string tsmiChangePassword {
            get {
                return ResourceManager.GetString("tsmiChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Support.
        /// </summary>
        internal static string tsmiContactSupport {
            get {
                return ResourceManager.GetString("tsmiContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor List Report.
        /// </summary>
        internal static string tsmiDoctorListReport {
            get {
                return ResourceManager.GetString("tsmiDoctorListReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tsmiExit {
            get {
                return ResourceManager.GetString("tsmiExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string tsmiFile {
            get {
                return ResourceManager.GetString("tsmiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tsmiHelp {
            get {
                return ResourceManager.GetString("tsmiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory And Medicine Revenue Report.
        /// </summary>
        internal static string tsmiInventoryAndMedicineRevenueReport {
            get {
                return ResourceManager.GetString("tsmiInventoryAndMedicineRevenueReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string tsmiLogin {
            get {
                return ResourceManager.GetString("tsmiLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string tsmiLogout {
            get {
                return ResourceManager.GetString("tsmiLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Appointments.
        /// </summary>
        internal static string tsmiManageAppointments {
            get {
                return ResourceManager.GetString("tsmiManageAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Doctors.
        /// </summary>
        internal static string tsmiManageDoctors {
            get {
                return ResourceManager.GetString("tsmiManageDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Examination History.
        /// </summary>
        internal static string tsmiManageExaminationHistory {
            get {
                return ResourceManager.GetString("tsmiManageExaminationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Medicine Inventory.
        /// </summary>
        internal static string tsmiManageMedicineInventory {
            get {
                return ResourceManager.GetString("tsmiManageMedicineInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string tsmiManagement {
            get {
                return ResourceManager.GetString("tsmiManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Patient.
        /// </summary>
        internal static string tsmiManagePatient {
            get {
                return ResourceManager.GetString("tsmiManagePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Prescriptions.
        /// </summary>
        internal static string tsmiManagePrescriptions {
            get {
                return ResourceManager.GetString("tsmiManagePrescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Accounts.
        /// </summary>
        internal static string tsmiManageUserAccounts {
            get {
                return ResourceManager.GetString("tsmiManageUserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Visit.
        /// </summary>
        internal static string tsmiManageVisit {
            get {
                return ResourceManager.GetString("tsmiManageVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Examination.
        /// </summary>
        internal static string tsmiPatientExamination {
            get {
                return ResourceManager.GetString("tsmiPatientExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient List Report.
        /// </summary>
        internal static string tsmiPatientListReport {
            get {
                return ResourceManager.GetString("tsmiPatientListReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports..
        /// </summary>
        internal static string tsmiReports {
            get {
                return ResourceManager.GetString("tsmiReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string tsmiSystem {
            get {
                return ResourceManager.GetString("tsmiSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        internal static string tsmiUserGuide {
            get {
                return ResourceManager.GetString("tsmiUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Activity Log.
        /// </summary>
        internal static string tsmiViewActivityLog {
            get {
                return ResourceManager.GetString("tsmiViewActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirm Password.
        /// </summary>
        internal static string txtConfirmPassword_Holder {
            get {
                return ResourceManager.GetString("txtConfirmPassword_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string txtEmail_Holder {
            get {
                return ResourceManager.GetString("txtEmail_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string txtPassword_Holder {
            get {
                return ResourceManager.GetString("txtPassword_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Security Answer.
        /// </summary>
        internal static string txtSecurityAnswer_Holder {
            get {
                return ResourceManager.GetString("txtSecurityAnswer_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string txtUserName {
            get {
                return ResourceManager.GetString("txtUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        internal static string txtUserName_Holder {
            get {
                return ResourceManager.GetString("txtUserName_Holder", resourceCulture);
            }
        }
    }
}
